export const OPTION_WORDLIMIT = 'option/OPTION_WORDLIMIT'
export const OPTION_REMOVELINEBREAKS = 'option/OPTION_REMOVELINEBREAKS'
export const OPTION_MODE = 'option/OPTION_MODE'
export const OPTION_KEYBOARD = 'option/OPTION_KEYBOARD'

export const SET_MESSAGE = 'autocue/SET_MESSAGE'
export const SET_LASTKEY_EVENT = 'autocue/SET_LASTKEY_EVENT'
export const START_WRITTING = 'autocue/START_WRITTING'
export const STOP_WRITTING = 'autocue/STOP_WRITTING'
export const SET_LETTERS = 'autocue/SET_LETTERS'

export const RESET_GAME = 'game/RESET_GAME'
export const START_GAME = 'game/START_GAME'
export const FINISH_GAME = 'game/FINISH_GAME'
export const INCREMENT_CHAR = 'game/INCREMENT_CHAR'
export const INCREMENT_SOFT_WRONG = 'game/INCREMENT_SOFT_WRONG'
export const INCREMENT_WRONG = 'game/INCREMENT_WRONG'

export const ADD_NOTIFICATION = 'notifications/ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'notifications/REMOVE_NOTIFICATION'
